USER = "abc"
PASSWORD = "xxx"

LOCAL_HOSTS = ["xx.xx.xx.xx"]
STAGING_HOSTS = ["xx.xx.xx.xx"]

EMAIL_HOST = "xxx"
EMAIL_PORT = "1"
EMAIL_HOST_USER = "xxx"
EMAIL_HOST_PASSWORD = "xxx"
DEFAULT_FROM_EMAIL = "xxx"
SERVER_EMAIL = "xxx"
SECRET_KEY = "xxx"
DATABASE_NAME = "xx"
DATABASE_USER = "xx"
DATABASE_USER_PASSWORD = "xx"
AWS_STORAGE_BUCKET_NAME = "xx"
AWS_ACCESS_KEY_ID = "xxxx"
AWS_SECRET_ACCESS_KEY = "x"
GOOGLE_API_KEY = "xxx"
